logging.level: error
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/lib/mysql/server_audit.log
  tags: ["db_audit"]

- type: log
  enabled: true
  paths:
    - /var/lib/mysql/slow-query.log
  tags: ["db_slow"]

output.logstash:
  hosts: [ "172.16.0.228:5444" ]

