name: Git-Action CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}

      - uses: actions/checkout@v3
      - name: BuildAndPushImage
        run: |
          docker build ./ -t ghcr.io/joohanhong/hongsnet-nginx:${{ github.run_number }}
          docker push ghcr.io/joohanhong/hongsnet-nginx:${{ github.run_number }}

      - name: Clone Repository
        run: |
          git clone https://joohan.hong:${{ secrets.GITLAB_TOKEN }}@gitlab.hongsnet.net/joohan.hong/argocd_test.git

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq

      - name: Update YAML File
        run: |
          yq -i '.image.tag = "ghcr.io/joohanhong/hongsnet-nginx:${{ github.run_number }}"' 'github-nginx/values.yaml'

      - name: Push to Repo
        run: |
          git config --global user.name "${{secrets.USERNAME_ARGOCD}}"
          git config --global user.email "${{secrets.EMAIL_ARGOCD}}"
          cd argocd-test-configs
          git add .
          git commit -m "Updated by GitHub Actions ${{ github.run_number }}"
          git push https://gitlab.hongsnet.net/joohan.hong/argocd_test.git --all

