name: BuildAndPushImageOnHarborAndUpdateArgoCDConfig

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: 
    steps:
    #- uses: hongsnet-nginx:latest
    - uses: owner/repo@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.CONTAINER_USERNAME }}
        password: ${{ secrets.CONTAINER_PASSWORD }}

    - uses: actions/checkout@v3
    - name: BuildAndPushImageOnHarbor
      run: |
        docker build ./ -t ghcr.io/joohanhong/hongsnet-nginx:${{ github.run_number }}
        docker push ghcr.io/joohanhong/hongsnet-nginx:${{ github.run_number }}

    - name: Clone Repository
      run: |
        git clone https://juhanida21@nate.com:7r6zjbUxrsuhRRLVBsve@gitlab.hongsnet.net/joohan.hong/argocd_test.git

    - name: Install yq
      run: |
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod a+x /usr/local/bin/yq

    - name: Update YAML File
      run: |
        yq -i '.image.tag = "ghcr.io/joohanhong/hongsnet-nginx:${{ github.run_number }}"' 'github-nginx/values.yaml'

    - name: Push to Repo
      run: |
        git config --global user.name "${{secrets.USERNAME_ARGOCD}}"
        git config --global user.email "${{secrets.EMAIL_ARGOCD}}"
        cd argocd-test-configs
        git add .
        git commit -m "Updated by GitHub Actions ${{ github.run_number }}"
        git push https://gitlab.hongsnet.net/joohan.hong/argocd_test.git --all

